name: syncthing
description: Syncthing client for Chrome OS
dependencies:
  forge:
    path: ../forge.dart
  chrome: any
  chrome_ssl:
    path: ../chrome_ssl.dart
  base32: any
  logging: any
  quiver: any
dev_dependencies:
  unittest: any
transformers:
- chrome
- $dart2js:
    $include: "web/main.dart"
    csp: true