name: syncthing
description: Syncthing client for Chrome OS
dependencies:
  forge: any
  chrome: any
  chrome_ssl:
    git: git://github.com/burnnat/chrome_ssl.dart.git
  polymer: any
  paper_elements: any
  base32: any
  logging: any
  quiver: any
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points: "web/index.html"
    csp: true
- $dart2js:
    $exclude: ["test/test.dart", "web/main_interface.dart"]
    csp: true
